// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using senai_eventPlus_webApi_codeFirst_jwt.Contexts;

#nullable disable

namespace senai_eventPlus_webApi_codeFirst_jwt.Migrations
{
    [DbContext(typeof(EventPlusContext))]
    [Migration("20231026191431_criacao-banco")]
    partial class criacaobanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.Property<Guid>("idComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("exibe")
                        .HasColumnType("BIT");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idComentario");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("Comentario");

                    b.HasData(
                        new
                        {
                            idComentario = new Guid("bad3be25-473d-40e4-ad27-ca9015f67ff2"),
                            descricao = "Excelente evento",
                            exibe = true,
                            idEvento = new Guid("da5ee12d-cdf8-4e82-bd88-47d23310e90b"),
                            idUsuario = new Guid("7403ec30-d3d6-4187-8343-22a55eb61b44")
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.Property<Guid>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataEvento")
                        .HasColumnType("DATE");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("horarioEvento")
                        .HasColumnType("TIME");

                    b.Property<Guid>("idInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idTipoEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nomeEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idEvento");

                    b.HasIndex("idInstituicao");

                    b.HasIndex("idTipoEvento");

                    b.ToTable("Evento");

                    b.HasData(
                        new
                        {
                            idEvento = new Guid("da5ee12d-cdf8-4e82-bd88-47d23310e90b"),
                            dataEvento = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            descricao = "Conceitos básicos do SQL Server, como DDL, DML, DQL.",
                            horarioEvento = new TimeSpan(0, 13, 0, 0, 0),
                            idInstituicao = new Guid("afc910e2-d5d2-4a39-b85e-538ee50afa5a"),
                            idTipoEvento = new Guid("64c88e66-4150-41b4-bf7d-112e04e51fa4"),
                            nomeEvento = "Introdução ao banco de dados SQL Server"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", b =>
                {
                    b.Property<Guid>("idInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("idInstituicao");

                    b.HasIndex("cnpj")
                        .IsUnique();

                    b.ToTable("Instituicao");

                    b.HasData(
                        new
                        {
                            idInstituicao = new Guid("afc910e2-d5d2-4a39-b85e-538ee50afa5a"),
                            cnpj = "1234567891012",
                            endereco = "Rua Niteroi 180",
                            nomeFantasia = "DevSchool",
                            razaoSocial = "Escola Internacional de Desenvolvimento"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.Property<Guid>("idPresencasEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idEvento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("situacao")
                        .HasColumnType("BIT");

                    b.HasKey("idPresencasEvento");

                    b.HasIndex("idEvento");

                    b.HasIndex("idUsuario");

                    b.ToTable("PresencasEvento");

                    b.HasData(
                        new
                        {
                            idPresencasEvento = new Guid("3b9ba71e-0696-4406-ba0b-a716ca419cd5"),
                            idEvento = new Guid("da5ee12d-cdf8-4e82-bd88-47d23310e90b"),
                            idUsuario = new Guid("7403ec30-d3d6-4187-8343-22a55eb61b44"),
                            situacao = true
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", b =>
                {
                    b.Property<Guid>("idTiposEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTiposEvento");

                    b.HasIndex("tipoEvento")
                        .IsUnique();

                    b.ToTable("TiposEvento");

                    b.HasData(
                        new
                        {
                            idTiposEvento = new Guid("64c88e66-4150-41b4-bf7d-112e04e51fa4"),
                            tipoEvento = "SQL Server"
                        },
                        new
                        {
                            idTiposEvento = new Guid("f1c2ce9c-bad5-4d24-8baf-0a9e2544a281"),
                            tipoEvento = "C#"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", b =>
                {
                    b.Property<Guid>("idTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idTipoUsuario");

                    b.HasIndex("tipoUsuario")
                        .IsUnique();

                    b.ToTable("TipoUsuario");

                    b.HasData(
                        new
                        {
                            idTipoUsuario = new Guid("6fd46c05-f80b-4fa2-9a9f-119475efe196"),
                            tipoUsuario = "Administrador"
                        },
                        new
                        {
                            idTipoUsuario = new Guid("632344c2-7f3e-4280-992f-03c6d3503a47"),
                            tipoUsuario = "Comum"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.Property<Guid>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<Guid>("idTipoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("idUsuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("idTipoUsuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idUsuario = new Guid("d6f297ae-38eb-49c1-a328-f4b629f938de"),
                            email = "allan@allan.com",
                            idTipoUsuario = new Guid("6fd46c05-f80b-4fa2-9a9f-119475efe196"),
                            nome = "Allan Rodrigues",
                            senha = "$2a$11$fdaIcbKzbQzdUhMhWLfyPON/wW/PeTjXmRAawaOrdde2jl7GAiwXO"
                        },
                        new
                        {
                            idUsuario = new Guid("7403ec30-d3d6-4187-8343-22a55eb61b44"),
                            email = "everton@everton.com",
                            idTipoUsuario = new Guid("632344c2-7f3e-4280-992f-03c6d3503a47"),
                            nome = "Everton Araujo",
                            senha = "$2a$11$tl/p3i9P00tHfMPUFjdneePHAjgVLiGEK7f7ll4gMU7ysBfsPrnbG"
                        });
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Comentario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Instituicao", "instituicao")
                        .WithMany()
                        .HasForeignKey("idInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposEvento", "tipoEvento")
                        .WithMany()
                        .HasForeignKey("idTipoEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("instituicao");

                    b.Navigation("tipoEvento");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.PresencasEvento", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("idEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("senai_eventPlus_webApi_codeFirst_jwt.Domains.Usuario", b =>
                {
                    b.HasOne("senai_eventPlus_webApi_codeFirst_jwt.Domains.TiposUsuario", "tiposUsuario")
                        .WithMany()
                        .HasForeignKey("idTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiposUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
